spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/mealdb
spring.datasource.username=postgres
spring.datasource.password=941116
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
